
name: Muhammad Murtaza

# 
description: Student Of Fast University Id:21k-4758

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/murtazaHussainn/murtazaHussainn.github.io/master/images/avatar.jpg


footer-links:
  email: k214758@nu.edu.pk
  facebook: /murtaza.hussain.1675
  github: murtazaHussainn/murtazaHussainn.github.io
  instagram: murtazahussain._




url: https://murtazahussainn.github.io


#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

version: v1.2.0

kramdown:
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'


sass:
  style: :expanded # You might prefer to minify using :compressed

gems:
  - jekyll-sitemap 
  - jekyll-feed 

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
